<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollector>true</ServerGarbageCollector>
    <ConcurrentGarbageCollector>true</ConcurrentGarbageCollector>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\SocketServerLib\SocketServerLib.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>